name: CICD

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'alpha'
      - 'beta'
      - 'dev'
  pull_request:
    types: [opened, reopened, synchronize]
  merge_group:

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5
      with:
        global-json-file: global.json

    - name: .NET Build
      run: dotnet build -c Release

    - name: Set up Docker Compose
      uses: docker/setup-compose-action@v1

    - name: Add hosts to /etc/hosts
      run: |
          sudo echo "127.0.0.1 oidc-server-mock" | sudo tee -a /etc/hosts
          curl -sSL https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

    - name: .NET Test
      working-directory: tests/pam_oidc_auth_tests
      run: dotnet run -c Release /p:DebugSymbols=true /p:DebugType=full -- --report-xunit-trx --report-xunit-trx-filename test-results.trx --coverage --coverage-output-format cobertura --coverage-output coverage.cobertura.xml

    - name: Test Report
      uses: dorny/test-reporter@v2
      if: success() || failure()
      with:
        name: pam_oidc_auth Tests
        path: tests/**/TestResults/test-results.trx
        reporter: dotnet-trx

    - name: Coverage
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.cobertura.xml
        fail_ci_if_error: false

    - name: Run Benchmark
      working-directory: benchmarks/pam_oidc_auth_benchmarks
      run: |
        docker-compose -f ../../tests/pam_oidc_auth_tests/docker-compose.yaml up -d
        dotnet run -c Release

  publish-matrix:
    name: Publish Installers
    runs-on: ${{ matrix.runs-on }}
    needs: [build-test]
    environment: production
    strategy:
      matrix:
        include:
          - rid: linux-x64
            runs-on: ubuntu-latest
          - rid: linux-arm64
            runs-on: ubuntu-24.04-arm
          - rid: linux-musl-x64
            runs-on: ubuntu-latest
          - rid: linux-musl-arm64
            runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v5

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json

      - name: Publish ${{ matrix.rid }}
        working-directory: src/pam_oidc_auth
        run: dotnet publish -r ${{ matrix.rid }} -o bin/publish

      - uses: actions/upload-artifact@v5
        with:
          name: pam_oidc_auth-${{ matrix.rid }}
          path: src/pam_oidc_auth/bin/publish/

  create-release:
    if: ${{ github.event_name != 'pull_request' }}
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-test, publish-matrix]
    steps:
    - uses: actions/checkout@v5

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Download artifacts
      uses: actions/download-artifact@v6
      with:
        path: dist/

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v4
      id: semantic
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        extra_plugins: |
          conventional-changelog-conventionalcommits
